#include "haikang_model.h"
#include "common_define.h"
#include <unordered_map>

//海康设备型号定义
static std::unordered_map<int, std::string> haikang_device_model_map;

static onceToken token([]() {
	haikang_device_model_map.emplace(1, "尚未定义的DVR类型");
	haikang_device_model_map.emplace(2, "ATM DVR");
	haikang_device_model_map.emplace(3, "DVS");
	haikang_device_model_map.emplace(4, "6001D");
	haikang_device_model_map.emplace(5, "6001F");
	haikang_device_model_map.emplace(6, "8000HC");
	haikang_device_model_map.emplace(7, "8000HT");
	haikang_device_model_map.emplace(8, "8000HF");
	haikang_device_model_map.emplace(9, "8000HS DVR(no audio)");
	haikang_device_model_map.emplace(10, "8016HTS DVR(no audio)");
	haikang_device_model_map.emplace(11, "HB DVR(SATA HD)");
	haikang_device_model_map.emplace(12, "8000HCS DVR");
	haikang_device_model_map.emplace(13, "带ATA硬盘的DVS");
	haikang_device_model_map.emplace(14, "8000HC-S");
	haikang_device_model_map.emplace(15, "8000HT-S");
	haikang_device_model_map.emplace(16, "8000HF-S");
	haikang_device_model_map.emplace(17, "8000HS-S");
	haikang_device_model_map.emplace(18, "ATM-S");
	haikang_device_model_map.emplace(19, "7000H系列");
	haikang_device_model_map.emplace(20, "多路解码器");
	haikang_device_model_map.emplace(21, "mobile DVR");
	haikang_device_model_map.emplace(22, "8000HD-S");
	haikang_device_model_map.emplace(23, "8000HD-SL");
	haikang_device_model_map.emplace(24, "8000HC-SL");
	haikang_device_model_map.emplace(25, "8000HS_ST");
	haikang_device_model_map.emplace(26, "6000HW");
	haikang_device_model_map.emplace(27, "多路解码器");
	haikang_device_model_map.emplace(28, "640X高清解码器");
	haikang_device_model_map.emplace(29, "610X解码器");
	haikang_device_model_map.emplace(30, "标清网络摄像机");
	haikang_device_model_map.emplace(31, "高清网络摄像机");
	haikang_device_model_map.emplace(32, "X62MF系列摄像机");
	haikang_device_model_map.emplace(35, "智能交通摄像机");
	haikang_device_model_map.emplace(36, "智能分析高清网络摄像机(人脸抓拍机)");
	haikang_device_model_map.emplace(38, "一体机");
	haikang_device_model_map.emplace(40, "IP标清快球");
	haikang_device_model_map.emplace(41, "IP 200万高清快球");
	haikang_device_model_map.emplace(42, "IP 130万高清快球");
	haikang_device_model_map.emplace(43, "IP 高清智能快球");
	haikang_device_model_map.emplace(44, "红外热成像摄像机");
	haikang_device_model_map.emplace(45, "红外热成像双目球机");
	haikang_device_model_map.emplace(46, "球型鹰眼（大）");
	haikang_device_model_map.emplace(47, "非球型鹰眼（小）");
	haikang_device_model_map.emplace(48, "称重数据管理服务器");
	haikang_device_model_map.emplace(50, "IP 模块");
	haikang_device_model_map.emplace(51, "交通智能云台（不带雷达测速）");
	haikang_device_model_map.emplace(52, "交通智能云台（带雷达测速）");
	haikang_device_model_map.emplace(60, "6501 车牌识别");
	haikang_device_model_map.emplace(61, "智能ATM");
	haikang_device_model_map.emplace(62, "双摄像机跟踪：DS6002-HF/B");
	haikang_device_model_map.emplace(63, "异常行为识别：DS6101-HF/B");
	haikang_device_model_map.emplace(64, "智能分析仪");
	haikang_device_model_map.emplace(65, "9000智能");
	haikang_device_model_map.emplace(66, "海鑫人脸抓拍 ATM");
	haikang_device_model_map.emplace(67, "私有人脸抓拍 ATM");
	haikang_device_model_map.emplace(68, "9100智能");
	haikang_device_model_map.emplace(69, "智能行为IP摄像机");
	haikang_device_model_map.emplace(70, "智能人脸IP摄像机");
	haikang_device_model_map.emplace(71, "DS71XXH_S");
	haikang_device_model_map.emplace(72, "DS72XXH_S");
	haikang_device_model_map.emplace(73, "DS73XXH_S");
	haikang_device_model_map.emplace(74, "DS72XX_HF_S");
	haikang_device_model_map.emplace(75, "DS73XX_HFI_S");
	haikang_device_model_map.emplace(76, "DS76XX_H_S");
	haikang_device_model_map.emplace(77, "DS76XX_N_S");
	haikang_device_model_map.emplace(78, "机柜智能检测仪");
	haikang_device_model_map.emplace(81, "DS81XX_HS_S");
	haikang_device_model_map.emplace(82, "DS81XX_HL_S");
	haikang_device_model_map.emplace(83, "DS81XX_HC_S");
	haikang_device_model_map.emplace(84, "DS81XX_HD_S");
	haikang_device_model_map.emplace(85, "DS81XX_HE_S");
	haikang_device_model_map.emplace(86, "DS81XX_HF_S");
	haikang_device_model_map.emplace(87, "DS81XX_AH_S");
	haikang_device_model_map.emplace(88, "DS81XX_AHF_S");
	haikang_device_model_map.emplace(90, "DS90XX_HF_S");
	haikang_device_model_map.emplace(91, "DS91XX_HF_S");
	haikang_device_model_map.emplace(92, "91XXHD-S(MD)");
	haikang_device_model_map.emplace(93, "9000智能 ATM");
	haikang_device_model_map.emplace(94, "9100智能 ATM");
	haikang_device_model_map.emplace(95, "DS95XXN-S NVR");
	haikang_device_model_map.emplace(96, "DS96XXN-SH NVR");
	haikang_device_model_map.emplace(97, "DS90XX_HF_SH");
	haikang_device_model_map.emplace(98, "DS91XX_HF_SH");
	haikang_device_model_map.emplace(100, "视频综合平台设备型号(X:编码板片数，Y:解码板片数)");
	haikang_device_model_map.emplace(101, "视频综合平台内部编码器");
	haikang_device_model_map.emplace(102, "视频综合平台内部解码器");
	haikang_device_model_map.emplace(103, "视频综合平台内部码分器");
	haikang_device_model_map.emplace(104, "视频综合平台内部光纤板");
	haikang_device_model_map.emplace(105, "65XXHC DVS");
	haikang_device_model_map.emplace(106, "65XXHC-SATA DVS");
	haikang_device_model_map.emplace(107, "65XXHF DVS");
	haikang_device_model_map.emplace(108, "65XXHF-SATA DVS");
	haikang_device_model_map.emplace(109, "65 rack DVS");
	haikang_device_model_map.emplace(110, "iVMS-6200(/C) 客流量统计");
	haikang_device_model_map.emplace(111, "IVMS_6200_B 异常行为识别");
	haikang_device_model_map.emplace(112, "72XXHV_ST15 DVR");
	haikang_device_model_map.emplace(113, "72XXHV_ST20 DVR");
	haikang_device_model_map.emplace(114, "IVMS-6200(/T)");
	haikang_device_model_map.emplace(115, "IVMS-6200(/BP)");
	haikang_device_model_map.emplace(116, "DS_81XXHC_ST");
	haikang_device_model_map.emplace(117, "DS_81XXHS_ST");
	haikang_device_model_map.emplace(118, "DS_81XXAH_ST");
	haikang_device_model_map.emplace(119, "DS_81XXAHF_ST");
	haikang_device_model_map.emplace(120, "DS_66XXDVS");
	haikang_device_model_map.emplace(121, "视频综合平台内部报警器");
	haikang_device_model_map.emplace(122, "视频综合平台内部级联输入");
	haikang_device_model_map.emplace(123, "视频综合平台内部级联输出");
	haikang_device_model_map.emplace(124, "视频综合平台内部智能");
	haikang_device_model_map.emplace(125, "V6高清");
	haikang_device_model_map.emplace(126, "V6级联不带DSP");
	haikang_device_model_map.emplace(127, "V6级联带DSP");
	haikang_device_model_map.emplace(128, "视频综合平台子域控制器");
	haikang_device_model_map.emplace(129, "视频综合平台域控制器");
	haikang_device_model_map.emplace(130, "VGA高清编码器");
	haikang_device_model_map.emplace(131, "视频综合平台内部标清解码器");
	haikang_device_model_map.emplace(132, "视频综合平台内部高清解码器");
	haikang_device_model_map.emplace(133, "视频综合平台内部VGA解码器");
	haikang_device_model_map.emplace(134, "视频综合平台SDI子板");
	haikang_device_model_map.emplace(135, "矩阵接入网关");
	haikang_device_model_map.emplace(136, "光端机SD");
	haikang_device_model_map.emplace(141, "网络码分类产品");
	haikang_device_model_map.emplace(142, "通用报警主机类产品");
	haikang_device_model_map.emplace(143, "家用报警主机");
	haikang_device_model_map.emplace(144, "自助银行报警主机");
	haikang_device_model_map.emplace(145, "动环监控报警主机");
	haikang_device_model_map.emplace(146, "1900系列报警主机");
	haikang_device_model_map.emplace(147, "视频报警主机");
	haikang_device_model_map.emplace(148, "ATM防护舱控制器");
	haikang_device_model_map.emplace(149, "紧急求助报警产品");
	haikang_device_model_map.emplace(150, "无线报警主机产品");
	haikang_device_model_map.emplace(151, "4G网络模块");
	haikang_device_model_map.emplace(152, "视频动环监控主机");
	haikang_device_model_map.emplace(161, "多屏控制器");
	haikang_device_model_map.emplace(162, "BNC处理器");
	haikang_device_model_map.emplace(163, "RGB处理器");
	haikang_device_model_map.emplace(164, "码流处理器");
	haikang_device_model_map.emplace(165, "显示处理器");
	haikang_device_model_map.emplace(166, "分布式服务器");
	haikang_device_model_map.emplace(171, "8104ATM");
	haikang_device_model_map.emplace(172, "65 ATM");
	haikang_device_model_map.emplace(173, "9000 智能RH");
	haikang_device_model_map.emplace(174, "9100 智能RH设备");
	haikang_device_model_map.emplace(175, "65 异常行为识别");
	haikang_device_model_map.emplace(176, "65 车牌识别");
	haikang_device_model_map.emplace(177, "IVMS-6200(/F)人脸分析仪");
	haikang_device_model_map.emplace(178, "iVMS-6200(/A)");
	haikang_device_model_map.emplace(179, "IVMS-6200(/F_S)人脸后检索分析仪");
	haikang_device_model_map.emplace(181, "DS90XX_HF_RH");
	haikang_device_model_map.emplace(182, "9100 RH设备");
	haikang_device_model_map.emplace(183, "78系列设备");
	haikang_device_model_map.emplace(185, "DVR_81XXHW_S");
	haikang_device_model_map.emplace(186, "DVR_81XXHW_ST");
	haikang_device_model_map.emplace(187, "DVR_91XXHW_ST");
	haikang_device_model_map.emplace(188, "DVR_91XX_ST");
	haikang_device_model_map.emplace(189, "DVR_81XX_ST");
	haikang_device_model_map.emplace(190, "DS81XXHDI_ST,DS81XXHE_ST");
	haikang_device_model_map.emplace(191, "DS73XXHI_ST");
	haikang_device_model_map.emplace(192, "审讯81SH，81SHF");
	haikang_device_model_map.emplace(193, "审讯81SNL");
	haikang_device_model_map.emplace(194, "NVR：DS96xxN_ST");
	haikang_device_model_map.emplace(195, "NVR：DS86xxN_ST");
	haikang_device_model_map.emplace(196, "DS80xxHF_ST");
	haikang_device_model_map.emplace(197, "DS90xxHF_ST");
	haikang_device_model_map.emplace(198, "NVR：DS76xxN_ST");
	haikang_device_model_map.emplace(199, "NVR：DS-9664N-RH、DS-9664N-RT");
	haikang_device_model_map.emplace(200, "编码卡服务器");
	haikang_device_model_map.emplace(201, "解码卡服务器");
	haikang_device_model_map.emplace(202, "PCNVR存储服务器");
	haikang_device_model_map.emplace(203, "CVR");
	haikang_device_model_map.emplace(204, "高清DVR：DS_91xxHFH_ST");
	haikang_device_model_map.emplace(205, "66高清编码器");
	haikang_device_model_map.emplace(210, "终端服务器");
	haikang_device_model_map.emplace(211, "视频分析记录仪");
	haikang_device_model_map.emplace(212, "IP可视对讲主机");
	haikang_device_model_map.emplace(213, "SAN(与CVR_SERVER相同的程序，只是模式不同)");
	haikang_device_model_map.emplace(301, "B11");
	haikang_device_model_map.emplace(302, "B12");
	haikang_device_model_map.emplace(303, "B11内部编码器");
	haikang_device_model_map.emplace(304, "B12内部编码器");
	haikang_device_model_map.emplace(305, "VGA高清");
	haikang_device_model_map.emplace(306, "VGA高清");
	haikang_device_model_map.emplace(307, "SDI");
	haikang_device_model_map.emplace(308, "SDI");
	haikang_device_model_map.emplace(309, "B11内部高清解码器");
	haikang_device_model_map.emplace(310, "B11内部标清解码器");
	haikang_device_model_map.emplace(311, "B12内部标清解码器");
	haikang_device_model_map.emplace(312, "B11内部VGA解码器");
	haikang_device_model_map.emplace(313, "B12内部VGA解码器");
	haikang_device_model_map.emplace(314, "B10 RGB高清");
	haikang_device_model_map.emplace(315, "B10 DVI高清");
	haikang_device_model_map.emplace(316, "B10 HDMI高清");
	haikang_device_model_map.emplace(317, "B11 RGB高清");
	haikang_device_model_map.emplace(318, "B11 DVI高清");
	haikang_device_model_map.emplace(319, "B11 HDMI高清");
	haikang_device_model_map.emplace(320, "B12 RGB高清");
	haikang_device_model_map.emplace(321, "B12 DVI高清");
	haikang_device_model_map.emplace(322, "B12 HDMI高清");
	haikang_device_model_map.emplace(323, "B10 netra高清解码");
	haikang_device_model_map.emplace(324, "B10 netra高清编码");
	haikang_device_model_map.emplace(328, "B11 netra高清解码");
	haikang_device_model_map.emplace(329, "B12 netra高清解码");
	haikang_device_model_map.emplace(330, "B11 netra高清编码");
	haikang_device_model_map.emplace(331, "B12 netra高清编码");
	haikang_device_model_map.emplace(332, "视频综合平台内部高清解码器");
	haikang_device_model_map.emplace(333, "视频综合平台转码子系统");
	haikang_device_model_map.emplace(335, "视频综合平台万能解码板");
	haikang_device_model_map.emplace(336, "X86服务器子系统");
	haikang_device_model_map.emplace(337, "增强型解码板_SDI(B10)");
	haikang_device_model_map.emplace(338, "SDI输入编码子系统");
	haikang_device_model_map.emplace(340, "联网网关中的子系统");
	haikang_device_model_map.emplace(341, "联网网关中的子系统");
	haikang_device_model_map.emplace(342, "光口交换子系统");
	haikang_device_model_map.emplace(343, "智能子系统");
	haikang_device_model_map.emplace(344, "智能子系统");
	haikang_device_model_map.emplace(345, "netra编码(VGA)");
	haikang_device_model_map.emplace(346, "netra编码(DVI)");
	haikang_device_model_map.emplace(347, "netra编码(HDMI)");
	haikang_device_model_map.emplace(348, "光纤接入编码");
	haikang_device_model_map.emplace(349, "netra高清解码");
	haikang_device_model_map.emplace(350, "X86转码子系统");
	haikang_device_model_map.emplace(351, "netra编码");
	haikang_device_model_map.emplace(352, "x86服务器子系统");
	haikang_device_model_map.emplace(353, "一体机");
	haikang_device_model_map.emplace(355, "BNC输入编码子系统");
	haikang_device_model_map.emplace(356, "SDI输入编码子系统");
	haikang_device_model_map.emplace(358, "RGB输入编码子系统");
	haikang_device_model_map.emplace(361, "光纤输入编码子系统");
	haikang_device_model_map.emplace(362, "BNC输出解码子系统");
	haikang_device_model_map.emplace(363, "SDI输出解码子系统");
	haikang_device_model_map.emplace(365, "BNC输入编码子系统");
	haikang_device_model_map.emplace(366, "SDI输入编码子系统");
	haikang_device_model_map.emplace(367, "VGA输入编码子系统");
	haikang_device_model_map.emplace(368, "RGB输入编码子系统");
	haikang_device_model_map.emplace(369, "DVI输入编码子系统");
	haikang_device_model_map.emplace(370, "HDMI输入编码子系统");
	haikang_device_model_map.emplace(371, "BNC输出解码子系统");
	haikang_device_model_map.emplace(372, "SDI输出解码子系统");
	haikang_device_model_map.emplace(373, "BNC输入编码子系统");
	haikang_device_model_map.emplace(375, "SDI输入编码子系统");
	haikang_device_model_map.emplace(376, "VGA输入编码子系统");
	haikang_device_model_map.emplace(377, "RGB输入编码子系统");
	haikang_device_model_map.emplace(378, "DVI输入编码子系统");
	haikang_device_model_map.emplace(379, "HDMI输入编码子系统");
	haikang_device_model_map.emplace(380, "BNC输出解码子系统");
	haikang_device_model_map.emplace(381, "金融行业一体机X86子系统");
	haikang_device_model_map.emplace(382, "智能楼宇一体机X86子系统");
	haikang_device_model_map.emplace(384, "增强型解码板_SDI(B11)");
	haikang_device_model_map.emplace(385, "增强型解码板_SDI(B12)");
	haikang_device_model_map.emplace(400, "B20主控板");
	haikang_device_model_map.emplace(401, "SDI输入编码");
	haikang_device_model_map.emplace(402, "光纤输入高清编码");
	haikang_device_model_map.emplace(403, "DVI解码");
	haikang_device_model_map.emplace(404, "HDMI解码");
	haikang_device_model_map.emplace(405, "VGA解码");
	haikang_device_model_map.emplace(406, "B20解码子系统");
	haikang_device_model_map.emplace(407, "VGA编码板");
	haikang_device_model_map.emplace(408, "B20主控");
	haikang_device_model_map.emplace(409, "B20主控子板");
	haikang_device_model_map.emplace(410, "BNC解码子系统");
	haikang_device_model_map.emplace(411, "SDI解码子系统");
	haikang_device_model_map.emplace(412, "BNC编码子系统");
	haikang_device_model_map.emplace(413, "DVI编码子系统");
	haikang_device_model_map.emplace(414, "HDMI编码子系统");
	haikang_device_model_map.emplace(415, "X86服务器子系统");
	haikang_device_model_map.emplace(416, "YUV编码子系统");
	haikang_device_model_map.emplace(417, "HW编码子系统");
	haikang_device_model_map.emplace(418, "DS_B20N128Fx_M级联板");
	haikang_device_model_map.emplace(419, "IO主控板");
	haikang_device_model_map.emplace(420, "VGA编码");
	haikang_device_model_map.emplace(421, "VGA解码");
	haikang_device_model_map.emplace(422, "DVI解码");
	haikang_device_model_map.emplace(423, "HDMI解码");
	haikang_device_model_map.emplace(424, "视频增强板");
	haikang_device_model_map.emplace(425, "3G SID编码");
	haikang_device_model_map.emplace(426, "B20解码子系统");
	haikang_device_model_map.emplace(427, "X86服务器子系统");
	haikang_device_model_map.emplace(428, "DVI双链路");
	haikang_device_model_map.emplace(429, "相机拼接类型");
	haikang_device_model_map.emplace(431, "TVI");
	haikang_device_model_map.emplace(432, "交换机子系统");
	haikang_device_model_map.emplace(433, "超高清X86输入");
	haikang_device_model_map.emplace(436, "光端机接入子系统");
	haikang_device_model_map.emplace(437, "级联子系统");
	haikang_device_model_map.emplace(438, "网络光纤子系统");
	haikang_device_model_map.emplace(439, "超高清解码子系统");
	haikang_device_model_map.emplace(440, "B21主控");
	haikang_device_model_map.emplace(441, "B21机箱 x = A/S/D");
	haikang_device_model_map.emplace(442, "B21编码子系统");
	haikang_device_model_map.emplace(443, "B21解码子系统");
	haikang_device_model_map.emplace(444, "B21 X86子系统");
	haikang_device_model_map.emplace(501, "C10S 集中式大屏控制器");
	haikang_device_model_map.emplace(551, "SDI处理器");
	haikang_device_model_map.emplace(552, "8路BNC处理器");
	haikang_device_model_map.emplace(553, "显示处理器");
	haikang_device_model_map.emplace(554, "TVI输入板");
	haikang_device_model_map.emplace(555, "DVI 2路输入板");
	haikang_device_model_map.emplace(556, "DVI，HDMI，VGA输出板带音频");
	haikang_device_model_map.emplace(557, "DVI，HDMI，VGA输入板带音频");
	haikang_device_model_map.emplace(570, "分布式大屏控制器");
	haikang_device_model_map.emplace(571, "BNC输入设备");
	haikang_device_model_map.emplace(572, "DVI输入设备");
	haikang_device_model_map.emplace(573, "DP输入设备");
	haikang_device_model_map.emplace(574, "输出设备");
	haikang_device_model_map.emplace(601, "报警主机百兆网络模块");
	haikang_device_model_map.emplace(602, "室内机");
	haikang_device_model_map.emplace(603, "门口机");
	haikang_device_model_map.emplace(604, "管理机");
	haikang_device_model_map.emplace(605, "别墅门口机");
	haikang_device_model_map.emplace(701, "64-T高清解码器");
	haikang_device_model_map.emplace(703, "65万能解码器");
	haikang_device_model_map.emplace(704, "63-T标清解码器");
	haikang_device_model_map.emplace(705, "抓屏服务器");
	haikang_device_model_map.emplace(706, "DS-64xxHD-S高清解码器");
	haikang_device_model_map.emplace(707, "多功能视音频转码器");
	haikang_device_model_map.emplace(708, "65D-T万能解码器");
	haikang_device_model_map.emplace(709, "65HD-T万能解码器");
	haikang_device_model_map.emplace(710, "69XXUD超高清解码器");
	haikang_device_model_map.emplace(711, "65XXUD解码器");
	haikang_device_model_map.emplace(712, "65XXUD_L解码器");
	haikang_device_model_map.emplace(713, "65XXUD_T解码器");
	haikang_device_model_map.emplace(750, "LCD屏幕 解码卡");
	haikang_device_model_map.emplace(751, "SDI矩阵");
	haikang_device_model_map.emplace(752, "LCD屏幕解码卡");
	haikang_device_model_map.emplace(760, "LED屏发送卡");
	haikang_device_model_map.emplace(770, "视频会议服务器");
	haikang_device_model_map.emplace(771, "视频会议终端");
	haikang_device_model_map.emplace(772, "视频会议一体式终端");
	haikang_device_model_map.emplace(773, "互动教学终端");
	haikang_device_model_map.emplace(800, "虚拟屏服务器");
	haikang_device_model_map.emplace(850, "门禁主机");
	haikang_device_model_map.emplace(851, "指纹一体机");
	haikang_device_model_map.emplace(852, "经济型门禁主机");
	haikang_device_model_map.emplace(854, "经济型门禁一体机");
	haikang_device_model_map.emplace(856, "汉军指纹门禁一体机");
	haikang_device_model_map.emplace(857, "人员通道主机");
	haikang_device_model_map.emplace(858, "经济型指纹门禁产品");
	haikang_device_model_map.emplace(859, "分布式三层架构门禁主机");
	haikang_device_model_map.emplace(860, "分布式三层架构就地控制器");
	haikang_device_model_map.emplace(861, "视屏门禁一体机");
	haikang_device_model_map.emplace(862, "经济型指纹门禁产品");
	haikang_device_model_map.emplace(863, "人脸抓拍门禁一体机");
	haikang_device_model_map.emplace(864, "梯控主控制器");
	haikang_device_model_map.emplace(865, "梯控分控制器");
	haikang_device_model_map.emplace(870, "立式/台式智能身份识别终端");
	haikang_device_model_map.emplace(900, "68M合码器");
	haikang_device_model_map.emplace(901, "信息发布主机");
	haikang_device_model_map.emplace(902, "信息发布服务器");
	haikang_device_model_map.emplace(931, "背投显示设备");
	haikang_device_model_map.emplace(951, "光纤收发器");
	haikang_device_model_map.emplace(952, "百兆交换机");
	haikang_device_model_map.emplace(971, "屏幕服务器");
	haikang_device_model_map.emplace(972, "OPS电脑盒");
	haikang_device_model_map.emplace(1001, "IP 200万一体化云台");
	haikang_device_model_map.emplace(1002, "鱼眼摄像机");
	haikang_device_model_map.emplace(1003, "经济型鱼眼摄像机");
	haikang_device_model_map.emplace(1004, "双目摄像机");
	haikang_device_model_map.emplace(1010, "支持365的平台的IPC CAM");
	haikang_device_model_map.emplace(1011, "支持A5S的平台的IPC CAM");
	haikang_device_model_map.emplace(1012, "支持385的平台的IPC CAM");
	haikang_device_model_map.emplace(1013, "支持R2的平台的IPC CAM");
	haikang_device_model_map.emplace(1014, "支持8127的平台的IPC CAM");
	haikang_device_model_map.emplace(1015, "支持S2的平台的IPC CAM");
	haikang_device_model_map.emplace(1110, "支持365的平台的IPD CAM");
	haikang_device_model_map.emplace(1111, "支持A5S的平台的IPD CAM");
	haikang_device_model_map.emplace(1112, "支持385的平台的IPD CAM");
	haikang_device_model_map.emplace(1113, "支持R2的平台的IPD CAM");
	haikang_device_model_map.emplace(1114, "支持8127的平台的IPD CAM");
	haikang_device_model_map.emplace(1115, "支持S2的平台的IPD CAM");
	haikang_device_model_map.emplace(1211, "支持8127的平台的ITCCAM");
	haikang_device_model_map.emplace(1300, "无人机基站设备（Ummanned Aerial Vehicle ? Station）");
	haikang_device_model_map.emplace(1400, "出入口终端服务器");
	haikang_device_model_map.emplace(1401, "停车场服务器");
	haikang_device_model_map.emplace(1402, "TME出入口控制机");
	haikang_device_model_map.emplace(2001, "混合DVR：DS-90xxHW-ST");
	haikang_device_model_map.emplace(2002, "DS-72xxHV-SH，DS-72xxHF-SH");
	haikang_device_model_map.emplace(2003, "DS-92xxHF-ST");
	haikang_device_model_map.emplace(2004, "Netra DVR: DS-91xxHF-XT");
	haikang_device_model_map.emplace(2005, "Netra 混合DVR: DS-90xxHF-XT");
	haikang_device_model_map.emplace(2006, "Netra DVR: DS-73xxHX-SH");
	haikang_device_model_map.emplace(2007, "Netra DVR: DS-72xxHFH-ST");
	haikang_device_model_map.emplace(2008, "DVS: DS-67xxHF-SATA");
	haikang_device_model_map.emplace(2009, "DVS: DS-67xxHW");
	haikang_device_model_map.emplace(2010, "DVS: DS-67xxHW-SATA");
	haikang_device_model_map.emplace(2011, "DVS: DS-67xxHF");
	haikang_device_model_map.emplace(2012, "DVR: DS-72xxHF-SV");
	haikang_device_model_map.emplace(2013, "DVR: DS-72xxHW-SV");
	haikang_device_model_map.emplace(2014, "DVR: DS-81xxHX-SH");
	haikang_device_model_map.emplace(2015, "DVR: DS-71xxHX-SL");
	haikang_device_model_map.emplace(2016, "DVR: DS-76xxH-ST");
	haikang_device_model_map.emplace(2017, "DVR: DS-73xxHFH-ST");
	haikang_device_model_map.emplace(2018, "DVR: DS-81xxHFH-ST");
	haikang_device_model_map.emplace(2019, "DVR: DS-72xxHFH-SL");
	haikang_device_model_map.emplace(2020, "2盘位ATM");
	haikang_device_model_map.emplace(2100, "iDS-9100HF-ST/A");
	haikang_device_model_map.emplace(2101, "iDS-9100HF-ST/B");
	haikang_device_model_map.emplace(2102, "iDS-9000HF-ST/A");
	haikang_device_model_map.emplace(2103, "iDS-9000HF-ST/B");
	haikang_device_model_map.emplace(2104, "iDS-8100HF-ST/A");
	haikang_device_model_map.emplace(2105, "iDS-8100HF-ST/B");
	haikang_device_model_map.emplace(2106, "iDS-8000HF-ST/A");
	haikang_device_model_map.emplace(2107, "iDS-8000HF-ST/B");
	haikang_device_model_map.emplace(2108, "智能混合ATM机");
	haikang_device_model_map.emplace(2109, "垂直双目相机");
	haikang_device_model_map.emplace(2201, "Netra NVR: DS-77xxN-ST");
	haikang_device_model_map.emplace(2202, "Netra NVR: DS-95xxN-ST");
	haikang_device_model_map.emplace(2203, "Netra NVR: DS-85xxN-ST");
	haikang_device_model_map.emplace(2204, "Netra NVR: DS-96xxN-XT");
	haikang_device_model_map.emplace(2205, "Netra NVR: DS-76xxN-SE、DS-78xxN-SH");
	haikang_device_model_map.emplace(2206, "Netra 审讯NVR，包括4种类型：DS-8608SNL-SP、DS-8608SNL-ST、DS-8608SN-SP、DS-8608SN-ST，L表示带LCD，P表POE");
	haikang_device_model_map.emplace(2207, "Netra NVR: DS-96xxN-RX");
	haikang_device_model_map.emplace(2208, "DS-71XXN-SL 民用产品");
	haikang_device_model_map.emplace(2209, "CS_N1_1XX，民用事业部所用");
	haikang_device_model_map.emplace(2210, "71XX_N_SN 经济型民用产品");
	haikang_device_model_map.emplace(2211, "N1_2XX 民用事业部所用");
	haikang_device_model_map.emplace(2212, "76XX_N_SHT");
	haikang_device_model_map.emplace(2213, "高新性能NVR(256路)");
	haikang_device_model_map.emplace(2214, "76/78N-EX(/N/P)系列NVR，包括4/8/16路的E1一盘位设备和8/16/32路的E2两盘位设备");
	haikang_device_model_map.emplace(2215, "77N-E4(/N/P)系列NVR，包括8/16/32路设备");
	haikang_device_model_map.emplace(2216, "86N-E8(/N/P)系列NVR，包括8/16/32路设备");
	haikang_device_model_map.emplace(2217, "DS_9616N_H8");
	haikang_device_model_map.emplace(2218, "72系列无线DVR产品（其中72后面的xx表示通道数，E后面的X表示的是盘位数，G XY表示的是无线类型）");
	haikang_device_model_map.emplace(2219, "76系列无线NVR产品（其中76后面的xx表示通道数，E后面的X表示的是盘位数，G XY表示的是无线类型）");
	haikang_device_model_map.emplace(2220, "XVR: 72HGH-SH系列4路");
	haikang_device_model_map.emplace(2221, "XVR: 72HGH-SH系列8路16路、72HQH-SH系列");
	haikang_device_model_map.emplace(2222, "XVR: 73HGH-SH系列、73HQH-SH系列");
	haikang_device_model_map.emplace(2223, "XVR: 81HGH-SH系列、81HQH-SH系列");
	haikang_device_model_map.emplace(2224, "XVR: 71HGH-SH系列4路");
	haikang_device_model_map.emplace(2225, "XVR: 71HGH-SH系列8路16路、71HQH-SH系列");
	haikang_device_model_map.emplace(2226, "便携式主机");
	haikang_device_model_map.emplace(2230, "96N-Fx系列NVR，包括8/16/32路设备");
	haikang_device_model_map.emplace(2231, "86N-Fx系列NVR，包括8/16/32路设备");
	haikang_device_model_map.emplace(2232, "96xxxN-Hx系列NVR");
	haikang_device_model_map.emplace(2233, "86N_I系列NVR");
	haikang_device_model_map.emplace(2234, "77N_I系列NVR");
	haikang_device_model_map.emplace(2235, "76N_I系列NVR");
	haikang_device_model_map.emplace(2236, "78N_I系列NVR");
	haikang_device_model_map.emplace(2237, "96xxxN-Ix系列NVR（DS-96128N-I16、DS-96128N-I24、DS-96256N-I16、DS-96256N-I24）");
	haikang_device_model_map.emplace(2238, "DS-9016HQH-XT");
	haikang_device_model_map.emplace(2301, "iVMS-4200的存储服务器");
	haikang_device_model_map.emplace(2401, "IVMS-6200 交通诱导分析仪");
	haikang_device_model_map.emplace(2402, "IVMS-6200 交通取证分析仪");
	haikang_device_model_map.emplace(2403, "iVMS-6200(/D)");
	haikang_device_model_map.emplace(2405, "iDS-81xxAHW-ST");
	haikang_device_model_map.emplace(2406, "iDS-81xxAHW-SP");
	haikang_device_model_map.emplace(2407, "iDS-81xxAHWL-ST");
	haikang_device_model_map.emplace(2408, "iDS-81xxAHWL-SP");
	haikang_device_model_map.emplace(2409, "iDS_9616N_H8");
	haikang_device_model_map.emplace(2500, "IVMS_6200_SMD");
	haikang_device_model_map.emplace(2501, "81HW-ST混合ATM DVR");
	haikang_device_model_map.emplace(2502, "81HW-SP混合ATM DVR");
	haikang_device_model_map.emplace(2503, "81AHWL-ST混合ATM DVR");
	haikang_device_model_map.emplace(2504, "81AHWL-SP混合ATM DVR");
	haikang_device_model_map.emplace(2601, "TVI ATM机");
	haikang_device_model_map.emplace(6101, "KY2017平台审讯机DS-8104SHFH（L）-K4/4P");
	haikang_device_model_map.emplace(6201, "标准庭审主机DS-8116THFHL-F4");
	haikang_device_model_map.emplace(6301, "DS_81XXAHQ_E4(TVI ATM)");
	haikang_device_model_map.emplace(6302, "IDS_81XXAHQ_E4(智能TVI ATM)");
	haikang_device_model_map.emplace(7502, "超脑智能NVR(人体识别)");
	haikang_device_model_map.emplace(7503, "超脑加油站NVR");
	haikang_device_model_map.emplace(7504, "人脸超脑智能NVR");
	haikang_device_model_map.emplace(7505, "86系列安全帽检测NVR产品：IDS-8632NX-I8/B");
	haikang_device_model_map.emplace(8451, "全景细节相机");
	haikang_device_model_map.emplace(11501, "监所智能服务器");
	haikang_device_model_map.emplace(12502, "67系列录播NVS产品");
	haikang_device_model_map.emplace(12503, "录播NVS行业专业产品");
	haikang_device_model_map.emplace(12505, "67系列安全帽检测NVS产品：iDS-6708NX/B");
	haikang_device_model_map.emplace(13001, "脸谱单机");
	haikang_device_model_map.emplace(13002, "猎鹰服务器");
	haikang_device_model_map.emplace(13003, "脸谱纯分析");
	haikang_device_model_map.emplace(13004, "人脸静态数据服务器");
	haikang_device_model_map.emplace(13005, "抓拍检测服务器");
	haikang_device_model_map.emplace(13006, "刀锋");
	haikang_device_model_map.emplace(13007, "模型对比服务器");
	haikang_device_model_map.emplace(13501, "智能锁盒子");
    }, []() {
		haikang_device_model_map.clear();
    });

std::string HaikangDeviceModel::ModelName(int model) {
	if (haikang_device_model_map.find(model) != haikang_device_model_map.end()) {
		return haikang_device_model_map.find(model)->second;
	}

	return "非法的设备型号";
}